In [10]:
import torch

#入门操作


#张量表示一个由数值组成的数组,这个数组有多个维度(轴)。具有一个轴的张量被称为一维张量,也是向量,具有两个轴的张量被称为二维张量,也被称为矩阵;
#1.创建一个行向量
x = torch.arange(12)
#创建一个3行12列的向量y
y = torch.arange(36).reshape(6,6)
print(x)
print(y)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])


In [11]:
#2.通过张量的shape属性来访问张量(沿每个轴的长度)的形状(shape)
print(x.shape)

print(y.shape)

torch.Size([12])
torch.Size([6, 6])


In [12]:
#3.张量中所有元素的总数,即形状的所有元素的乘积
print(x.numel())

print(y.numel())

12
36


In [15]:
#4.改变张量的的形状不会改变张量的大小
x = x.reshape(3,4)
print(x)
print(x.size())
print(x.shape)
print(x.numel())

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])
torch.Size([3, 4])
12


In [18]:
#5.初始化一个形状为(2,3,4)的全0矩阵
x1 = torch.zeros(2,3,4)
print(x1)
print(x1.size())
print(x1.shape)
print(x1.numel())


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([2, 3, 4])
torch.Size([2, 3, 4])
24


In [21]:
# 6.创建一个形状(4,5,6)的全1张量
x2 = torch.ones(4,5,6)
print(x2)

tensor([[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]])


In [24]:
# 7.创建一个形状(2,3,4)的全7张量
x3 = torch.full((2,3,4),12.55)
print(x3)

tensor([[[12.5500, 12.5500, 12.5500, 12.5500],
         [12.5500, 12.5500, 12.5500, 12.5500],
         [12.5500, 12.5500, 12.5500, 12.5500]],

        [[12.5500, 12.5500, 12.5500, 12.5500],
         [12.5500, 12.5500, 12.5500, 12.5500],
         [12.5500, 12.5500, 12.5500, 12.5500]]])


In [25]:
# 8. 通过某个特定的概率分布中随机采样得到张量中每个元素的值
x4 = torch.rand(2,3,4)
print(x4)

tensor([[[0.7501, 0.1935, 0.4423, 0.0946],
         [0.4901, 0.1479, 0.1345, 0.1842],
         [0.0355, 0.3902, 0.8388, 0.2128]],

        [[0.8913, 0.8281, 0.6978, 0.3319],
         [0.2565, 0.9783, 0.6660, 0.1881],
         [0.5428, 0.0240, 0.4216, 0.5138]]])


In [33]:
# 9. 生成形状为(2,3,4)的张量,元素值都介于1-30的随机浮点数
x5 = torch.rand(2, 3, 4) * (30 - 1) + 1
print(x5)

tensor([[[14.2161, 17.1181, 12.9961,  4.7713],
         [24.5101,  3.5115,  7.0955,  3.4238],
         [20.9394,  9.6562, 24.7328, 20.5763]],

        [[ 7.3723, 20.2162,  3.4120, 20.3365],
         [ 7.5057,  4.6908,  7.9663, 19.4453],
         [16.1598, 25.9486, 20.5807, 29.8412]]])


In [34]:
# 10.创建一个形状为(3,4)的张量,每个元素都从均值为0,标准差为1的标准搞死分布(正态分布)中随机取样
x6 = torch.rand(3,4)
print(x6)

tensor([[0.8666, 0.9443, 0.3296, 0.9996],
        [0.9647, 0.6011, 0.5072, 0.2359],
        [0.1515, 0.3344, 0.1584, 0.2950]])
