In [5]:
#运算符
#1.对于任意具有相同形状的张量,常见的标准算术运算符(+,-,*,/,**)都可以被升级为按元素运算

import torch
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x ** y)

str = "结束分隔符"
print(f"=========={str}=========")
print(y ** x)

#求幂运算(对张量中的每个元素求幂)
print(torch.exp(x))

tensor([ 3.,  4.,  6., 10.])
tensor([-1.,  0.,  2.,  6.])
tensor([ 2.,  4.,  8., 16.])
tensor([0.5000, 1.0000, 2.0000, 4.0000])
tensor([ 1.,  4., 16., 64.])
==========结束分隔符=========
tensor([  2.,   4.,  16., 256.])
tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])


In [ ]:
# 2.张量的链接